name: 测试

on: push

jobs:
  demo:
    runs-on: ubuntu-20.04
    name: 测试
    steps:
      - name: 下载
        uses: actions/checkout@v2
      - name: 测试
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: php扩展
        run: php -m
      - name: php版本
        run: php -v
      - name: php-cs-fixer版本
        run: php-cs-fixer -V
