name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  modules:
    description: '模块标签'
    required: true
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
