name: Campfire模块

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  check_label:
    name: Label检测
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'campfire_unit_test') || contains(github.event.pull_request.labels.*.name, 'campfire_function_test')
    steps:
      - run: echo 这里是Label检测
  code_format:
    name: 代码格式化
    runs-on: ubuntu-latest
    needs:
      - check_label
    steps:
      - run: echo 这里是代码格式化
  unit_test:
    name: 单元测试
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'campfire_unit_test')
    needs:
      - code_format
    steps:
      - run: echo 运行了单元测试
  function_test:
    name: 功能测试
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'campfire_function_test')
    needs:
      - code_format
    steps:
      - run: echo 运行了功能测试
  union_test:
    name: 联合测试
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'campfire_unit_test') || contains(github.event.pull_request.labels.*.name, 'campfire_function_test')
    needs:
      - code_format
    steps:
      - run: echo 运行了联合测试
