name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go env
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Test Print
        run: echo "这是一个自定义环境变量 ${{secrets.MY_TEST}}"

      - name: Test Print Undefined
        run: echo "这是一个自定义环境变量 ${{secrets.HHHH}}"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Test
        run: go test ./...

      - name: Test Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./c.out
        run: |
          go test -coverprofile=c.out
          bash <(curl -s https://codecov.io/bash) -Z -f c.out
