name: Demo

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
    branches:
      - develop

env:
  NAME: hello

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello World action step
        id: hello
        uses: DevDavid1307/hello-world-javascript-action@v1.9.7
        with:
          include: 'campfire, drive'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  test:
    runs-on: ubuntu-latest
    if: ${{ needs.hello_world_job.result }} == 'success'
    needs:
      - hello_world_job
    steps:
      - name: Print ${{ env.NAME }}
        run: echo 123 ${{ job.status }} - ${{ runner.os }} - ${{ needs.hello_world_job.result }}
