name: Test Context

on:
  pull_request:
    types:
      - opened

jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Campfire模块
        if: contains( github.event.pull_request.labels.*.name, 'campfire')
        run: echo 这里是Campfire模块
      - name: Drive模块
        if: contains( github.event.pull_request.labels.*.name, 'drive')
        run: echo Drive模块

