name: Demo

on:
  push:
    branches:
      - demo

env:
  NAME: hello

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print ${{ env.NAME }}
        run: echo 123 ${{ job.status }}
