name: Demo

on:
  push:
    branches:
      - demo

env:
  NAME: hello

jobs:
  parent:
    runs-on: ubuntu-latest
    steps:
      - run: echo parent
    outputs:
      result: parent
  test:
    runs-on: ubuntu-latest
    needs:
      - parent
    steps:
      - name: Print ${{ env.NAME }}
        run: echo 123 ${{ job.status }} - ${{ runner.os }} - ${{ needs.parent.outputs.result}}
