name: php环境

on: push

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: 拉取分支
        uses: actions/checkout@v2
      - name: 测试Context
        run: echo ${{ toJson(github) }}
#      - name: php环境
#        uses: ./.github/actions/setup-unit-test
#        with:
#          tools: php-cs-fixer
