name: php环境

on: push

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: 拉取分支
        uses: actions/checkout@v2
      - name: php环境
        uses: ./.github/actions/setup-unit-test
        with:
          php-version: '8.0'
          tools: php-cs-fixer
