name: 测试

on: push

env:
  hello: campfire
  include: ams

jobs:
  demo:
    runs-on: ubuntu-latest
    name: 测试
    steps:
      - name: 打印分支
        if: contains(env.hello, env.include)
        run: echo ${{ github.ref }} - ${{ env.hello }}
      - name: check composer version
        run: composer -V
      - name: check php version
        run: php -v
      - name: check phpunit version
        run: phpunit --version
      - name: php 扩展
        run: php -m
