name: 测试

on: push

jobs:
  demo:
    runs-on: ubuntu-20.04
    name: 测试
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 初始化环境
        uses: shivammathur/setup-php@v2
        with:
          extensions: psr
      - name: php扩展
        run: php -m
