name: 测试

on: push

jobs:
  demo:
    runs-on: ubuntu-20.04
    name: 测试
    steps:
      - name: 拉取分支
        uses: actions/checkout@v2
      - name: php环境
        uses: ./.github/actions/setup-php
        with:
          php-version: '7.4'
      - name: 下载php-cs-fixer
        run: sudo curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o ~/php-cs-fixer
      - name: 测试
        run: sudo ls -l ~
      - name: 版本
        run: sudo chmod a+x ~/php-cs-fixer && ~/php-cs-fixer -V
