name: 测试

on: push

jobs:
  demo:
    runs-on: ubuntu-20.04
    name: 测试
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 初始化环境
        run: |
          sudo pecl install psr
          cat $(php --ini | grep "(php.ini)" | sed -e "s|.*: s*||")/php.ini
