name: 测试

on: push

env:
  hello: campfire
  include: ams

jobs:
  demo:
    runs-on: ubuntu-20.04
    name: 测试
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: temp
        run: pwd
      - name: 打印分支
        if: contains(env.hello, env.include)
        run: echo ${{ github.ref }} - ${{ env.hello }}
      - name: check composer version
        run: composer -V
      - name: check php version
        run: php -v
      - name: check pecl version
        run: pecl version
      - name: check pecl ext
        run: pecl list
      - name: install psr ext
        run: pecl install psr
      - name: check phpunit version
        run: phpunit --version
      - name: php 扩展
        run: php -m
