name: 测试

on: push

env:
  hello: campfire
  include: ams

jobs:
  demo:
    runs-on: ubuntu-20.04
    name: 测试
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 准备php环境
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: swoole, psr, redis
          tools: php-cs-fixer, phpunit, composer:v2
          coverage: xdebug
      - name: php版本
        run: php -v
